# Generated by Django 4.2.7 on 2023-11-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identification_num',
            new_name='id_num',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='provice',
            new_name='province',
        ),
    ]
